# Generated by Django 2.2.2 on 2020-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('logid', models.BigAutoField(db_column='LogId', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=15)),
                ('password', models.TextField(db_column='Password')),
                ('markedfordeletion', models.BooleanField(db_column='MarkedForDeletion', default=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=30)),
            ],
        ),
    ]
