# Generated by Django 2.2.2 on 2020-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.BigAutoField(db_column='CommentId', primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=30)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postId', models.BigAutoField(db_column='PostId', primary_key=True, serialize=False)),
                ('posts', models.TextField()),
                ('createdAt', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='UserPostMapping',
            fields=[
                ('logid', models.BigAutoField(db_column='LogId', primary_key=True, serialize=False)),
                ('userId', models.IntegerField(db_column='UserId')),
                ('postId', models.IntegerField(db_column='PostId')),
            ],
            options={
                'db_table': 'UserPostMapping',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.BigAutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30)),
                ('password', models.TextField(db_column='Password')),
                ('markedfordeletion', models.BooleanField(db_column='MarkedForDeletion', default=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=30)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
