# Generated by Django 2.2.2 on 2020-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.TextField(default='--'),
        ),
        migrations.AddField(
            model_name='posts',
            name='subtitle',
            field=models.TextField(default='--'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.TextField(default='Anonymous User'),
        ),
    ]
